### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by jthoward64** [icon11-community/Folder11#33]
Right now the repo has a de facto [no license](https://choosealicense.com/no-permission/), it would be nice to get it under Creative Commons or MIT or unlicense or something

**Comment by nouvist** [comment]
that's the thing. initially it was MIT licensed. but most of the icons are logo of others which we couldn't claim that as licensed under the MIT _I guess_. so I don't really know what license supposed to, that's why I removes the license.

I'm planning to just add "logo/names used in icons mostly trademarked or registered trademarks of their respective holders. do not use for commercial use or something." but I'm not really sure.

**Comment by nouvist** [comment]
I think I add desclaimer to the README like what you saying.

https://github.com/icon11-community/Folder11/blob/6d6cddfe09683f83e1a64c34c93da86f57a614ff/README.md?plain=1#L5

thanks for your suggestion.
